name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Type check
        run: yarn check:type
      - name: Run unit tests
        run: yarn test:unit
      - name: Check package exports
        run: yarn test:exports
      - name: Check package contents
        run: npm pack --dry-run --json
      - name: Publish to npm
        run: npm publish
        env:
          CI: true
